name: smart_alert_dialog
description: A Smart Alert Dialog that uses Cupertino for IOS and Material for Android. Fell Free to colaborate, every PR is welcome!
repository: https://github.com/lcsvcn/smart_alert_dialog.git
homepage: https://github.com/lcsvcn/smart_alert_dialog.git
version: 4.0.4

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  universal_io: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.3.0

flutter:
  uses-material-design: true
