name: smart_alert_dialog
description: A Smart Alert Dialog that uses Cupertino for IOS and Material for Android. Fell Free to colaborate, every PR is welcome!
repository: https://github.com/lcsvcn/smart_alert_dialog.git
homepage: https://github.com/lcsvcn/smart_alert_dialog.git
version: 2.1.2-nullsafety.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
